---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jboss
  name: jboss
  namespace: jboss
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: jboss
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jboss
    spec:
      containers:
      - image: qregistry.redhat.io/jboss-eap-8/eap8-openjdk17-runtime-openshift-rhel8@sha256:442b2ded6bcd286d2a9297bd472c7edc015ba0aa30d897b9c01b5f07c4c4f86
        name: jboss
        resources: {}
---
